### ISSUE TITLE
Alternative web frontend

### ISSUE THREAD

**Issue by erlend-sh** [Zaechus/kingslayer#8]
First of all, congrats on a fully working Rust game, even running seamlessly in any browser, including mobile 👏 

I don’t know exactly how you’re doing it but you appear to be using a browser-native window feature. While I appreciate the minimalism, there does appear to be a lot to gain with an alternative, richer interface that could live behind a feature flag:

- Much better (and actual control over-) styling
- Better use of screen real estate
- Interactive features, e.g. auto completion/suggestions of commands

Probably there are far more lightweight ways to accomplish this, but you might wanna check out https://github.com/hecrj/iced  which has a demo of its web runtime here: https://iced.rs/

**Comment by Maxgy** [comment]
Thanks for interest and advice! I agree that the input method and overall styling of the page needs to change. TBH, the web demo is running an older version of kingslayer until I remove the compilation of rayon from WASM builds. After I fix this, I'll be sur eto take a look at use iced or something like yew.

**Comment by Zaechus** [comment]
It's not complete yet of course, but the new web interface at [kingslayer-web](https://zaechus.github.io/kingslayer-web/) is well underway and uses input fields and divs to accept user input and output the game instead of `prompt` and `alert`.
