### ISSUE TITLE
Can't close window on Firefox iOS

### ISSUE THREAD

**Issue by erlend-sh** [Zaechus/kingslayer#9]
If I run this game on Firefox iOS, I can't close the window or open other ones, because Firefox has the text box take over the entire app window.

![IMG_0643](https://user-images.githubusercontent.com/583842/73884269-d0c9bc00-4865-11ea-92e5-c24dd5bedbc7.jpg)

Upon clicking `Cancel` I get this:
![IMG_0644](https://user-images.githubusercontent.com/583842/73884265-ce676200-4865-11ea-96c9-6cd59103f935.jpg)

I also get this `I don't know the word "null".` error message upon clicking `Cancel` in Safari on iOS, but there the whole browser window doesn't get hijacked so I can easily just close the tab to terminate the process.

I do **not** get this error message on MacBook Firefox or Chrome, but I **do** get it in Safari.

**Comment by Maxgy** [comment]
This is an interesting issue that I hadn't found since I only tested on Firefox for Android. I figured this might happen on other systems, but haven't had a chance to use a less obtrusive input method. I will eventually remove the need for the prompt box.

**Comment by Zaechus** [comment]
The web version still uses prompt box, but a `quit` command was added in 642b15d that should stop the game. The actual change will be applied to [Zaechus/kingslayer-web](https://github.com/Zaechus/kingslayer-web) later.
